- name: aws variable assertions
  assert:
    that:
    - cuckoo_resultserver_ip is defined
    - aws_access_key is defined
    - aws_secret_key is defined
    - virt_platform is defined

- name: copy aws.conf template to cuckoo server
  template:
    src: templates/aws.conf
    dest: "{{ cuckoo_conf_dir }}/aws.conf"

- name: copy cuckoo.conf template to cuckoo server
  template:
    src: templates/cuckoo.conf
    dest: "{{ cuckoo_conf_dir }}/cuckoo.conf"
    
